"use client";

import Link from "next/link";
import {
  ArrowRight, BarChart3, Check, ChevronDown, CircleHelp, FileText, GraduationCap,
  Layers, ListChecks, Menu, MonitorPlay, MonitorSmartphone, Moon, ScrollText,
  Sparkles, Sun, Timer, TrendingUp, Upload, X,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useTheme } from "next-themes";
import { getCurrentUser } from "@/lib/api";
import Logo from "@/components/brand/Logo";

const container = "mx-auto w-full max-w-7xl px-6 lg:px-8";
const card = "rounded-2xl border hairline bg-[var(--surface)]";
const softTile = "grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--active-nav)] text-[var(--active-nav-text)]";

function ThemeButton() {
  const { resolvedTheme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  useEffect(() => { const frame = window.requestAnimationFrame(() => setMounted(true)); return () => window.cancelAnimationFrame(frame); }, []);
  const dark = resolvedTheme === "dark";
  return <button type="button" aria-label="Switch theme" title="Switch theme" onClick={() => setTheme(dark ? "light" : "dark")} className="grid h-11 w-11 place-items-center rounded-xl text-[var(--muted)] transition hover:bg-[var(--surface-muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">{mounted && dark ? <Sun size={18} /> : <Moon size={18} />}</button>;
}

function AuthCta({ compact = false, inverted = false }: { compact?: boolean; inverted?: boolean }) {
  const [loggedIn, setLoggedIn] = useState(false);
  useEffect(() => { getCurrentUser().then((user) => setLoggedIn(Boolean(user))); }, []);
  return <Link href={loggedIn ? "/dashboard" : "/register"} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-5 py-2.5 text-sm font-semibold transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] ${inverted ? "bg-[var(--surface)] text-[var(--primary-dark)]" : "bg-[var(--primary-action)] text-[var(--orange-button-text)] hover:bg-[var(--primary-dark)]"} ${compact ? "px-4" : ""}`}>{loggedIn ? "Go to dashboard" : "Get started"}<ArrowRight size={16} /></Link>;
}

function BrowserFrame({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <div className={`${card} overflow-hidden ${className}`}><div className="flex h-9 items-center gap-1.5 border-b hairline px-4"><span className="h-2 w-2 rounded-full border border-[var(--border)]" /><span className="h-2 w-2 rounded-full border border-[var(--border)]" /><span className="h-2 w-2 rounded-full border border-[var(--border)]" /></div>{children}</div>;
}

function SummaryMock({ compact = false }: { compact?: boolean }) {
  return <div className={`${card} p-4 ${compact ? "" : "h-full"}`}><div className="flex items-center gap-2 text-xs font-semibold text-[var(--primary-dark)]"><Sparkles size={14} /> AI summary</div><p className="mt-3 font-semibold">Process scheduling</p><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Scheduling decides which ready process receives the CPU. Round Robin improves responsiveness.</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-[var(--active-nav)] px-2 py-1 text-[10px] text-[var(--active-nav-text)]">CPU bursts</span><span className="rounded-full bg-[var(--active-nav)] px-2 py-1 text-[10px] text-[var(--active-nav-text)]">Time quantum</span></div><p className="mt-4 text-xs font-semibold">Key points</p><ul className="mt-2 space-y-1 text-xs text-[var(--muted)]"><li>• FCFS is simple to implement.</li><li>• Round Robin improves response time.</li><li>• Quantum size affects fairness.</li></ul></div>;
}

function QuizMock({ compact = false }: { compact?: boolean }) {
  const options = ["Round Robin", "FCFS", "SJF", "Priority"];
  return <div className={`${card} p-4 ${compact ? "" : "h-full"}`}><div className="flex items-center justify-between text-xs text-[var(--muted)]"><span>Question 2 of 5</span><span className="sr-only">40% complete</span></div><div className="mt-2 h-1 rounded-full bg-[var(--surface-muted)]"><div className="h-1 w-2/5 rounded-full bg-[var(--primary)]" /></div><p className="mt-4 text-sm font-semibold">Which algorithm uses a time quantum?</p><div className="mt-3 grid grid-cols-2 gap-2">{options.map((item, index) => <div key={item} className={`flex items-center gap-2 rounded-lg border px-2 py-2 text-xs ${index === 0 ? "border-[var(--primary)] bg-[var(--active-nav)] text-[var(--active-nav-text)]" : "hairline text-[var(--muted)]"}`}><span className="grid h-5 w-5 shrink-0 place-items-center rounded-md border border-current text-[10px] font-bold">{String.fromCharCode(65 + index)}</span>{item}{index === 0 && <Check size={13} className="ml-auto" />}</div>)}</div></div>;
}

function ScoreMock() {
  return <div className={`${card} flex items-center gap-3 p-4`}><div className="grid h-14 w-14 place-items-center rounded-full border-4 border-[var(--primary)] text-sm font-bold">4/5</div><div><p className="text-xs text-[var(--muted)]">Latest score</p><p className="font-semibold">Keep going</p></div></div>;
}

function HeroMockup() {
  return <BrowserFrame className="aspect-[5/4] w-full max-w-[640px] p-0"><div className="grid h-[calc(100%-2.25rem)] grid-cols-1 gap-4 overflow-hidden p-4 sm:grid-cols-[1.05fr_.95fr]"><SummaryMock /><div className="grid min-h-0 content-start gap-4"><QuizMock /><ScoreMock /></div></div></BrowserFrame>;
}

function MiniChart() {
  return <svg viewBox="0 0 320 100" className="mt-5 h-24 w-full" aria-hidden="true"><path d="M0 82 C35 78 48 70 75 72 S120 54 145 60 S190 40 220 46 S270 23 320 12 V100 H0Z" fill="var(--active-nav)" opacity=".7" /><path d="M0 82 C35 78 48 70 75 72 S120 54 145 60 S190 40 220 46 S270 23 320 12" fill="none" stroke="var(--primary)" strokeWidth="3" strokeLinecap="round" /></svg>;
}

function StepVisual({ step }: { step: number }) {
  if (step === 1) return <div className="flex items-center justify-center gap-3"><div className="rounded-lg border hairline bg-[var(--surface)] px-3 py-2 text-xs">notes.pdf</div><Upload size={18} className="text-[var(--primary)]" /></div>;
  if (step === 2) return <div className="space-y-2 rounded-xl border hairline bg-[var(--surface)] p-3"><div className="h-2 w-2/3 rounded bg-[var(--active-nav)]" /><div className="h-2 w-full rounded bg-[var(--surface-muted)]" /><div className="h-2 w-4/5 rounded bg-[var(--surface-muted)]" /></div>;
  if (step === 3) return <div className="flex justify-center gap-2"><div className="grid h-16 w-20 place-items-center rounded-lg border hairline bg-[var(--surface)] text-xs">Q</div><div className="grid h-16 w-20 place-items-center rounded-lg border hairline bg-[var(--surface)] text-xs">A</div></div>;
  return <div className="grid h-16 w-16 place-items-center rounded-full border-4 border-[var(--primary)] text-xs font-bold">4/5</div>;
}

function UseVisual({ type }: { type: "exam" | "lecture" | "self" }) {
  if (type === "exam") return <div className="flex items-end gap-2"><div className="h-14 w-8 rounded-t bg-[var(--active-nav)]" /><div className="h-20 w-8 rounded-t bg-[var(--primary)]" /><div className="h-11 w-8 rounded-t bg-[var(--active-nav)]" /></div>;
  if (type === "lecture") return <div className="space-y-2 rounded-lg border hairline bg-[var(--surface)] p-3"><div className="h-2 w-2/3 rounded bg-[var(--primary)]" /><div className="h-2 w-full rounded bg-[var(--surface-muted)]" /><div className="h-2 w-4/5 rounded bg-[var(--surface-muted)]" /></div>;
  return <div className="grid h-16 w-16 place-items-center rounded-full border-4 border-[var(--primary)] text-sm font-bold">05:00</div>;
}

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [preview, setPreview] = useState<"summary" | "quiz" | "progress">("summary");
  const [faq, setFaq] = useState(0);
  const [active, setActive] = useState("");
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const faqs = [["What can I upload?", "A PDF up to 10 MB, or text you paste in."], ["How are the quizzes made?", "An AI model reads your notes and writes questions from the text. Check the answers against your notes when you study."], ["Are my notes private?", "Your documents belong to your account and are not shown to other users."], ["Do I need an account?", "Yes. An account saves your documents, quiz results and progress."], ["Does it work on my phone?", "Yes. The layout is built for phones, tablets and desktops."]];
  useEffect(() => {
    const sections = ["features", "how-it-works", "faq"].map((id) => document.getElementById(id)).filter(Boolean) as HTMLElement[];
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
      setActive(visible?.target.id ?? "");
    }, { rootMargin: "-40% 0px -55% 0px" });
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  const tabs = [{ id: "summary", label: "Summary" }, { id: "quiz", label: "Quiz" }, { id: "progress", label: "Progress" }] as const;
  const moveTab = (index: number) => { const next = (index + tabs.length) % tabs.length; setPreview(tabs[next].id); tabRefs.current[next]?.focus(); };
  return <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]">
    <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-[var(--surface)] focus:px-4 focus:py-3">Skip to content</a>
    <header className="sticky top-0 z-50 border-b hairline bg-[var(--surface)]"><nav className={`${container} flex h-16 items-center justify-between gap-4`} aria-label="Main navigation"><Logo className="shrink-0 text-lg [&>span:first-child]:h-9 [&>span:first-child]:w-9" /><div className="hidden items-center gap-7 text-sm font-medium md:flex">{[["features", "Features"], ["how-it-works", "How it works"], ["faq", "FAQ"]].map(([id, label]) => <a key={id} href={`#${id}`} className={`border-b-2 py-2 transition ${active === id ? "border-[var(--primary)] text-[var(--primary)]" : "border-transparent text-[var(--muted)] hover:text-[var(--foreground)]"}`}>{label}</a>)}</div><div className="flex items-center gap-1"><ThemeButton /><Link href="/login" className="hidden min-h-11 items-center rounded-xl px-3 text-sm font-semibold text-[var(--muted)] hover:bg-[var(--surface-muted)] sm:inline-flex">Login</Link><span className="hidden sm:inline-flex"><AuthCta compact /></span><button type="button" onClick={() => setMenuOpen(true)} className="grid h-11 w-11 place-items-center rounded-xl md:hidden" aria-label="Open menu"><Menu size={20} /></button></div></nav></header>
    {menuOpen && <div className="fixed inset-0 z-[60] bg-[var(--foreground)]/30 md:hidden" onClick={() => setMenuOpen(false)}><div className="absolute inset-x-0 bottom-0 rounded-t-3xl border hairline bg-[var(--surface)] p-6 pb-[calc(1.5rem+env(safe-area-inset-bottom))]" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex items-center justify-between"><p className="font-semibold">Explore StudyAI</p><button onClick={() => setMenuOpen(false)} aria-label="Close menu" className="grid h-11 w-11 place-items-center rounded-xl"><X size={20} /></button></div><div className="space-y-1">{[["features", "Features"], ["how-it-works", "How it works"], ["faq", "FAQ"]].map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)} className="flex min-h-12 items-center rounded-xl px-3 font-medium hover:bg-[var(--surface-muted)]">{label}</a>)}<Link href="/login" className="flex min-h-12 items-center rounded-xl px-3 font-medium">Login</Link><AuthCta /></div></div></div>}
    <main id="main-content">
      <section className="relative overflow-hidden border-b hairline"><div className="pointer-events-none absolute inset-0 opacity-[.05] [background-image:linear-gradient(var(--border)_1px,transparent_1px),linear-gradient(90deg,var(--border)_1px,transparent_1px)] [background-size:32px_32px] [mask-image:radial-gradient(ellipse_at_top,black,transparent_72%)]" /><div className={`${container} relative grid gap-10 pb-14 pt-12 sm:pt-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-14 lg:pb-16 lg:pt-16`}><div><span className="inline-flex items-center gap-2 rounded-full border hairline bg-[var(--active-nav)] px-3 py-1.5 text-xs font-semibold text-[var(--active-nav-text)]"><Sparkles size={13} /> Study smarter with your own notes</span><h1 className="mt-6 max-w-[680px] text-balance text-[clamp(2.5rem,4.6vw,4rem)] font-bold leading-[1.05] tracking-tight">Turn your notes into a study guide.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[var(--muted)]">Upload a PDF or paste your notes. StudyAI writes the summary, builds flashcards, quizzes you, and tracks your progress.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><AuthCta /><a href="#how-it-works" className="inline-flex min-h-11 items-center justify-center rounded-xl border hairline px-5 py-2.5 text-sm font-semibold hover:bg-[var(--surface-muted)]">See how it works</a></div><ul className="mt-7 grid gap-3 text-sm text-[var(--muted)] sm:grid-cols-3 lg:grid-cols-1">{["Summaries in seconds", "Questions from your notes", "Progress you can see"].map((item) => <li key={item} className="flex items-center gap-2"><Check size={16} className="text-[var(--primary)]" />{item}</li>)}</ul></div><div className="flex justify-center lg:justify-end"><HeroMockup /></div></div></section>
      <section className={`${container} py-8`}><div className={`${card} grid overflow-hidden md:grid-cols-3`}>{[[ScrollText, "Long chapters are hard to review"], [Timer, "Writing your own quiz takes time"], [CircleHelp, "It’s unclear what you actually remember"]].map(([Icon, text], index) => <div key={text as string} className={`flex items-center gap-3 p-5 ${index > 0 ? "border-t hairline md:border-l md:border-t-0" : ""}`}><span className={softTile}><Icon size={18} /></span><p className="text-sm font-medium">{text as string}</p></div>)}</div></section>
      <section id="features" className={`${container} scroll-mt-20 py-16 lg:py-24`}><h2 className="text-4xl font-bold tracking-tight">A focused study loop.</h2><p className="mt-3 text-lg text-[var(--muted)]">From raw notes to confident recall, without the busywork.</p><div className="mt-10 grid gap-4 md:grid-cols-12"><article className={`${card} interactive p-6 md:col-span-7`}><span className={softTile}><Sparkles size={18} /></span><h3 className="mt-5 text-xl font-semibold">AI summary and key points</h3><p className="mt-2 text-sm text-[var(--muted)]">Get the structure of a chapter at a glance.</p><div className="mt-6 max-w-md"><SummaryMock compact /></div></article><article className={`${card} interactive p-6 md:col-span-5`}><span className={softTile}><ListChecks size={18} /></span><h3 className="mt-5 text-xl font-semibold">Quizzes from your notes</h3><p className="mt-2 text-sm text-[var(--muted)]">Practice with questions made from your own material.</p><div className="mt-6"><QuizMock compact /></div></article><article className={`${card} interactive p-6 md:col-span-4`}><span className={softTile}><Layers size={18} /></span><h3 className="mt-5 text-xl font-semibold">Flashcards</h3><p className="mt-2 text-sm text-[var(--muted)]">Turn key concepts into quick recall.</p><div className="flip-card mt-6 h-24 focus-within:outline-none"><div className="flip-inner relative h-full w-full"><div className="flip-front absolute inset-0 grid place-items-center rounded-xl border hairline bg-[var(--active-nav)] text-2xl font-bold text-[var(--active-nav-text)]">Q</div><div className="flip-back absolute inset-0 grid place-items-center rounded-xl border hairline bg-[var(--surface)] p-4 text-center text-sm">Round Robin shares CPU time fairly.</div></div></div></article><article className={`${card} interactive p-6 md:col-span-4`}><span className={softTile}><TrendingUp size={18} /></span><h3 className="mt-5 text-xl font-semibold">Progress tracking</h3><p className="mt-2 text-sm text-[var(--muted)]">See your scores improve over time.</p><MiniChart /></article><div className="grid gap-4 md:col-span-4"><article className={`${card} interactive p-5`}><span className={softTile}><FileText size={18} /></span><h3 className="mt-4 font-semibold">PDF or pasted text</h3><p className="mt-1 text-sm text-[var(--muted)]">Drop notes in and start studying.</p></article><article className={`${card} interactive p-5`}><span className={softTile}><MonitorSmartphone size={18} /></span><h3 className="mt-4 font-semibold">Works on any device</h3><p className="mt-1 text-sm text-[var(--muted)]">Pick up wherever you left off.</p></article></div></div></section>
      <section id="how-it-works" className={`${container} scroll-mt-20 py-16 lg:py-24`}><h2 className="text-4xl font-bold tracking-tight">A simple workflow.</h2><p className="mt-3 text-lg text-[var(--muted)]">Four calm steps from notes to momentum.</p><div className="relative mt-10 grid gap-8 md:grid-cols-4 md:gap-5 before:hidden md:before:absolute md:before:left-[12%] md:before:right-[12%] md:before:top-4 md:before:block md:before:border-t md:before:border-dashed md:before:border-[var(--border)]">{["Upload notes", "Get your guide", "Practice recall", "Track progress"].map((title, index) => <div key={title} className="relative"><div className="flex items-center gap-3"><span className="relative z-10 grid h-8 w-8 place-items-center rounded-full bg-[var(--primary)] text-sm font-bold text-[var(--orange-button-text)]">{index + 1}</span><h3 className="font-semibold">{title}</h3></div><div className="mt-4 grid h-[120px] place-items-center rounded-xl border hairline bg-[var(--active-nav)] p-5"><StepVisual step={index + 1} /></div></div>)}</div><div className="mt-8"><AuthCta /></div></section>
      <section className={`${container} py-16 lg:py-24`}><div className="flex flex-col gap-5 border-b hairline pb-6 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-4xl font-bold tracking-tight">Product preview.</h2><p className="mt-3 text-lg text-[var(--muted)]">A clear workspace built for focused study.</p></div><div role="tablist" aria-label="Product preview" className="flex max-w-full gap-5 overflow-x-auto">{tabs.map((tab, index) => <button key={tab.id} ref={(element) => { tabRefs.current[index] = element; }} type="button" role="tab" aria-selected={preview === tab.id} tabIndex={preview === tab.id ? 0 : -1} onClick={() => setPreview(tab.id)} onKeyDown={(event) => { if (event.key === "ArrowRight") moveTab(index + 1); if (event.key === "ArrowLeft") moveTab(index - 1); }} className={`whitespace-nowrap border-b-2 pb-3 text-sm font-semibold ${preview === tab.id ? "border-[var(--primary)] text-[var(--primary)]" : "border-transparent text-[var(--muted)]"}`}>{tab.label}</button>)}</div></div><BrowserFrame className="mt-8 min-h-[360px] p-5"><div className="h-[300px]">{preview === "summary" && <div className="mx-auto max-w-2xl"><SummaryMock /></div>}{preview === "quiz" && <div className="mx-auto max-w-2xl"><QuizMock /></div>}{preview === "progress" && <div className={`${card} mx-auto max-w-2xl p-5`}><div className="flex items-center gap-3"><span className={softTile}><BarChart3 size={18} /></span><div><p className="text-xs text-[var(--muted)]">Weekly progress</p><p className="font-semibold">Your recall is trending up</p></div></div><MiniChart /></div>}</div></BrowserFrame></section>
      <section className={`${container} py-16 lg:py-24`}><h2 className="text-4xl font-bold tracking-tight">Study in the way that fits.</h2><p className="mt-3 text-lg text-[var(--muted)]">A practical companion for the moments that matter.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{[[GraduationCap, "Exam revision", "Turn a whole chapter into questions you can actually practice.", "exam"], [MonitorPlay, "Lecture catch-up", "Summarize the slides and notes you missed.", "lecture"], [Timer, "Quick self-test", "Check what you remember in five focused minutes.", "self"]].map(([Icon, title, text, type]) => <article key={title as string} className={`${card} p-6`}><div className="grid h-24 place-items-center rounded-xl bg-[var(--active-nav)]"><UseVisual type={type as "exam" | "lecture" | "self"} /></div><div className="mt-5 flex items-center gap-3"><span className={softTile}><Icon size={18} /></span><h3 className="text-lg font-semibold">{title as string}</h3></div><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{text as string}</p></article>)}</div></section>
      <section id="faq" className={`${container} scroll-mt-20 py-16 lg:py-24`}><div className="grid gap-10 lg:grid-cols-[1fr_2fr]"><div><h2 className="text-4xl font-bold tracking-tight">Frequently asked questions.</h2><p className="mt-4 text-lg leading-7 text-[var(--muted)]">Can&apos;t find your answer? Create an account and try it with your own notes.</p><Link href="/register" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[var(--primary-dark)]">Get started <ArrowRight size={16} /></Link></div><div className={`${card} overflow-hidden`}>{faqs.map(([question, answer], index) => <div key={question} className="border-b hairline last:border-b-0"><button type="button" aria-expanded={faq === index} onClick={() => setFaq(faq === index ? -1 : index)} className="flex min-h-16 w-full items-center justify-between gap-4 px-5 py-5 text-left font-semibold">{question}<ChevronDown size={18} className={`shrink-0 transition-transform duration-200 ${faq === index ? "rotate-180" : ""}`} /></button><div className={`grid transition-[grid-template-rows,opacity] duration-200 ${faq === index ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`}><p className="min-h-0 overflow-hidden px-5 pb-5 text-sm leading-6 text-[var(--muted)]">{answer}</p></div></div>)}</div></div></section>
      <section className="relative overflow-hidden bg-[var(--primary-action)]"><div className="pointer-events-none absolute inset-0 opacity-[.06] [background-image:linear-gradient(white_1px,transparent_1px),linear-gradient(90deg,white_1px,transparent_1px)] [background-size:32px_32px]" /><div className={`${container} relative py-16 text-center lg:py-20`}><h2 className="text-4xl font-bold text-[var(--orange-button-text)]">Start with one chapter.</h2><p className="mx-auto mt-3 max-w-xl text-lg text-[var(--orange-button-text)]/75">Turn the notes you already have into your next study session.</p><div className="mt-7 flex justify-center"><AuthCta inverted /></div></div></section>
    </main>
    <footer className={`${container} py-12`}><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Logo className="text-base [&>span:first-child]:h-8 [&>span:first-child]:w-8 [&>span:first-child>svg]:h-4 [&>span:first-child>svg]:w-4" /><p className="mt-3 text-sm text-[var(--muted)]">AI study companion for students.</p></div><div><p className="text-sm font-medium text-[var(--muted)]">Product</p><div className="mt-4 space-y-3 text-sm text-[var(--muted)]"><a href="#features" className="block hover:text-[var(--foreground)]">Features</a><a href="#how-it-works" className="block hover:text-[var(--foreground)]">How it works</a><a href="#faq" className="block hover:text-[var(--foreground)]">FAQ</a></div></div><div><p className="text-sm font-medium text-[var(--muted)]">Account</p><div className="mt-4 space-y-3 text-sm text-[var(--muted)]"><Link href="/login" className="block hover:text-[var(--foreground)]">Login</Link><Link href="/register" className="block hover:text-[var(--foreground)]">Register</Link></div></div><div /></div><div className="mt-10 flex flex-col gap-4 border-t hairline pt-6 text-sm text-[var(--muted)] sm:flex-row sm:items-center sm:justify-between"><span>© 2026 StudyAI</span><ThemeButton /></div></footer>
  </div>;
}
