"use client";

import Link from "next/link";
import { AlertCircle, Check, Eye, EyeOff, KeyRound, Mail, UserRound } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import AuthShell from "@/components/auth/AuthShell";
import PasswordStrength from "@/components/auth/PasswordStrength";
import { Button } from "@/components/ui";
import { register } from "@/lib/api";

function Field({ icon: Icon, label, error, children, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { icon: typeof Mail; label: string; error?: string; children?: React.ReactNode }) {
  const errorId = error ? `${props.name}-error` : undefined;
  return <label className="block text-sm font-semibold text-[var(--muted)]">{label}<div className={`relative mt-2 flex h-12 items-center gap-2 rounded-xl border bg-[var(--surface)] px-3 transition-colors focus-within:bg-[var(--background)] focus-within:ring-2 focus-within:ring-[var(--primary)]/20 ${error ? "border-[var(--danger)] focus-within:border-[var(--danger)]" : "border-[var(--border)] focus-within:border-[var(--primary)]"}`}><Icon size={18} className="pointer-events-none shrink-0 text-[var(--muted)]"/>  <input {...props} aria-describedby={errorId} className="field-input h-full min-w-0 flex-1 border-0 bg-transparent p-0 text-base font-medium text-[var(--foreground)] outline-none ring-0 shadow-none placeholder:font-normal placeholder:text-[var(--muted)] focus:outline-none focus:ring-0 focus-visible:outline-none focus-visible:ring-0 lg:text-sm"/>{children}</div>{error && <span id={errorId} className="mt-1 flex items-center gap-1 text-xs text-[var(--danger)]"><AlertCircle size={13}/>{error}</span>}</label>;
}

export default function Register() {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name || !email || password.length < 6 || password !== confirm) { toast.error(password.length < 6 ? "Password must be at least 6 characters." : password !== confirm ? "Passwords do not match." : "Please complete all fields."); return; } setLoading(true); await register(name, email, password); toast.success("Account created!"); router.push("/dashboard"); };
  return <AuthShell><div className="mb-[clamp(.75rem,2vh,1.5rem)] text-center lg:text-left"><h2 className="text-[28px] font-bold tracking-tight text-[var(--foreground)]">Create your account</h2><p className="mt-2 text-[15px] text-[var(--muted)]">Start studying smarter today</p></div><form onSubmit={submit} className="space-y-[clamp(.5rem,1.25vh,.9rem)] lg:flex lg:flex-col lg:gap-4 lg:space-y-0"><Field icon={UserRound} label="Full name" name="name" autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Your full name" required/><Field icon={Mail} label="Email" name="email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" required/><Field icon={KeyRound} label="Password" name="password" type={show ? "text" : "password"} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 6 characters" required><button type="button" onClick={() => setShow(!show)} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-[var(--muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]" aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff size={18}/> : <Eye size={18}/>}</button></Field><PasswordStrength password={password}/><Field icon={KeyRound} label="Confirm password" name="confirm-password" type={show ? "text" : "password"} autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="Re-enter your password" required/>{confirm && password === confirm && <p className="flex items-center gap-1 text-xs text-[var(--success)]"><Check size={14}/>Passwords match</p>}{confirm && password !== confirm && <p className="flex items-center gap-1 text-xs text-[var(--danger)]"><AlertCircle size={13}/>Passwords do not match</p>}<Button loading={loading} className="mt-1 h-12 w-full rounded-xl text-base">Create account</Button></form><p className="mt-5 whitespace-nowrap text-center text-sm text-[var(--muted)]">Already have an account? <Link href="/login" className="font-bold text-[var(--primary-dark)]">Login</Link></p></AuthShell>;
}
