"use client";
import { Loader2, Inbox, CheckCircle2, type LucideIcon } from "lucide-react";
import { useEffect, useState } from "react";

export function Button({ children, variant = "primary", className = "", loading = false, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger" | "ghost"; loading?: boolean }) {
  const styles = { primary: "bg-[var(--primary-action)] text-[var(--orange-button-text)] shadow-lg shadow-[var(--primary-action)]/20 hover:bg-[var(--primary-dark)]", secondary: "border border-[var(--border)] bg-[var(--surface)] text-[var(--foreground)] hover:bg-[var(--surface-muted)]", danger: "border border-[var(--danger)]/30 bg-[var(--danger)]/10 text-[var(--danger)] hover:bg-[var(--danger)]/15 dark:border-[var(--danger)]/50 dark:bg-[var(--danger)]/20", ghost: "text-[var(--muted)] hover:bg-[var(--surface-muted)]" };
  return <button className={`inline-flex min-h-11 select-none items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition duration-150 hover:-translate-y-0.5 active:translate-y-0 active:scale-[.97] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <Loader2 size={16} className="animate-spin" />}{children}</button>;
}
export function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`premium-card rounded-2xl ${className}`}>{children}</div>; }
export function IconTile({ icon: Icon, variant = "soft", className = "" }: { icon: LucideIcon; variant?: "soft" | "solid"; className?: string }) { return <span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${variant === "solid" ? "bg-[var(--primary-action)] text-[var(--orange-button-text)]" : "bg-[var(--sky-soft)] text-[var(--primary-dark)] dark:bg-[var(--sky-deep)] dark:text-[var(--orange-button-text)]"} ${className}`}><Icon size={19} aria-hidden="true" /></span>; }
export function Badge({ children, tone = "blue" }: { children: React.ReactNode; tone?: "blue" | "green" | "amber" | "rose" | "slate" }) { const tones = { blue: "bg-[var(--orange-tint)] text-[var(--orange-text)] dark:bg-[var(--surface-muted)] dark:text-[var(--primary-light)]", green: "bg-green-50 text-green-700 dark:bg-green-950/50 dark:text-green-300", amber: "bg-[var(--warning)]/10 text-[var(--warning)] dark:bg-[var(--warning)]/20 dark:text-[var(--warning)]", rose: "bg-red-50 text-red-700 dark:bg-red-950/50 dark:text-red-300", slate: "bg-[var(--surface-muted)] text-[var(--muted)] dark:bg-[var(--surface-muted)] dark:text-[var(--muted)]" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span>; }
export function Input({ label, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label?: string; error?: string }) {
  const inputId = props.id ?? props.name;
  const errorId = error && inputId ? `${inputId}-error` : undefined;
  return <label htmlFor={inputId} className="block text-sm font-medium text-[var(--foreground)]">{label}{props.required && <span className="text-[var(--danger)]"> *</span>}<span className={`mt-2 flex h-12 items-center rounded-xl border bg-[var(--surface)] px-3 transition-colors focus-within:border-[var(--primary)] focus-within:bg-[var(--background)] focus-within:ring-2 focus-within:ring-[var(--primary)]/20 ${error ? "border-[var(--danger)] focus-within:border-[var(--danger)]" : "border-[var(--border)]"}`}><input {...props} id={inputId} aria-describedby={errorId ?? props["aria-describedby"]} className={`field-input h-full min-w-0 flex-1 rounded-none border-0 bg-transparent p-0 text-base font-medium text-[var(--foreground)] outline-none ring-0 shadow-none placeholder:font-normal placeholder:text-[var(--muted)] focus:outline-none focus:ring-0 focus-visible:outline-none focus-visible:ring-0 ${props.className ?? ""}`} /></span>{error && <span id={errorId} className="mt-1 block text-xs text-[var(--danger)]">{error}</span>}</label>;
}
export function ProgressBar({ value, className = "" }: { value: number; className?: string }) { return <div className={`h-2 overflow-hidden rounded-full bg-[var(--surface-muted)] dark:bg-[var(--surface-muted)] ${className}`}><div className="h-full rounded-full bg-[var(--primary)] transition-all duration-500" style={{ width: `${value}%` }} /></div>; }
export function ProgressRing({ value, size = 60, stroke = 6, children }: { value: number; size?: number; stroke?: number; children?: React.ReactNode }) { const radius = (size - stroke) / 2; const circumference = radius * 2 * Math.PI; return <div className="relative" style={{ width: size, height: size }}><svg width={size} height={size} className="-rotate-90"><circle cx={size/2} cy={size/2} r={radius} fill="none" stroke="currentColor" strokeWidth={stroke} className="text-[var(--surface-muted)] dark:text-[var(--surface-muted)]" /><circle cx={size/2} cy={size/2} r={radius} fill="none" stroke="var(--primary)" strokeWidth={stroke} strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={circumference - (value / 100) * circumference} className="transition-all duration-700" /></svg>{children && <div className="absolute inset-0 grid place-items-center">{children}</div>}</div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex min-h-[10rem] flex-col items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-6 py-8 text-center"><IconTile icon={Inbox} /><h3 className="mt-3 font-semibold text-[var(--foreground)]">{title}</h3><p className="mt-1 max-w-sm text-sm text-[var(--muted)]">{description}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
export function CountUp({ value, suffix = "", prefix = "" }: { value: number; suffix?: string; prefix?: string }) { const [current, setCurrent] = useState(0); useEffect(() => { const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches; let frame = 0; if (reduce) { frame = requestAnimationFrame(() => setCurrent(value)); return () => cancelAnimationFrame(frame); } const start = performance.now(); const duration = 500; const tick = (now: number) => { const progress = Math.min(1, (now - start) / duration); setCurrent(Math.round(value * progress)); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]); return <>{prefix}{current}{suffix}</>; }
export function Skeleton({ className = "" }: { className?: string }) { return <div className={`shimmer animate-pulse rounded-lg bg-[var(--border)] dark:bg-[var(--surface-muted)] ${className}`} />; }
export function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[var(--primary-dark)]/60 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-md rounded-t-2xl border border-[var(--border)] bg-[var(--surface)] p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] shadow-2xl sm:rounded-2xl sm:p-6"><div className="mx-auto mb-4 h-1.5 w-10 rounded-full bg-[var(--border)] sm:hidden" /><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-[var(--foreground)]">{title}</h3><button onClick={onClose} className="grid h-11 w-11 place-items-center rounded-xl text-2xl text-[var(--muted)] hover:bg-[var(--surface-muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]" aria-label="Close">×</button></div>{children}</div></div>; }
export function SuccessMark() { return <CheckCircle2 className="text-[var(--success)]" size={18} />; }
